# Generated by Django 3.1.7 on 2021-03-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210312_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benefits',
            new_name='Benefit',
        ),
    ]
