# Generated by Django 3.1.7 on 2021-03-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210312_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='category',
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
    ]
