# Generated by Django 3.1.7 on 2021-03-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210312_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='beneficios',
            field=models.TextField(default=True, max_length=600, verbose_name='Descrição'),
        ),
    ]
