# Generated by Django 3.1.7 on 2021-03-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_plan_beneficios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='beneficios',
        ),
    ]
