# Generated by Django 3.1.7 on 2021-03-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='Avaliação'),
        ),
    ]
