# Generated by Django 3.1.7 on 2021-03-14 01:07

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210314_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='img',
            field=stdimage.models.StdImageField(default=False, upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
